FROM library/postgres

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB postgres

COPY urlworkeradd/external/adapters/postgresrepo/migrations ./migrations
COPY urlworkeradd/external/adapters/postgresrepo/init-message-db.sh /docker-entrypoint-initdb.d/