#FROM golang:latest
FROM goeasydocker_url_shorterer AS build

WORKDIR /app

COPY envconfig .

#RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o main cmd/upload_vault_links.go
#EXPOSE 8200

FROM scratch
WORKDIR /
COPY --from=build app/main /main
EXPOSE 8200

ENTRYPOINT ["/main"]
CMD [""]


#CMD ["./vault"]
