#FROM golang:latest
FROM goeasydocker_url_shorterer AS build

WORKDIR /app

COPY datasplitter ./datasplitter
COPY envconfig ./envconfig
COPY urlworkerget ./urlworkerget
COPY urlworkeradd ./urlworkeradd
COPY storage ./storage
COPY metrics ./metrics
COPY go.work .
COPY go.work.sum .
#should create from new image with already built file not to blow size and time of dockerfiles
# and finally lets try to cache go libs

#RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build urlworkerget/cmd/main.go

FROM scratch
WORKDIR /
COPY --from=build app/main /main
EXPOSE 9090
EXPOSE 9095

ENTRYPOINT ["/main"]
CMD [""]

#EXPOSE 9090
#EXPOSE 9095

#CMD ["./url_worker_getter"]
