#FROM golang:latest
FROM goeasydocker_url_shorterer AS build

WORKDIR /app

COPY datasplitter ./datasplitter
COPY envconfig ./envconfig
COPY urlworkerget ./urlworkerget
COPY urlworkeradd ./urlworkeradd
COPY storage ./storage
COPY metrics ./metrics
COPY go.work .
COPY go.work.sum .

#RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build ./storage/cmd/main.go

FROM scratch
WORKDIR /
COPY --from=build app/main /main

ENTRYPOINT ["/main"]
CMD [""]


#CMD ["./main"]
